- hosts: app
  become_user: root
  vars_prompt:
  - name: "app_user_password"
    prompt: "Please enter the password of app user"
    private: yes
    confirm: yes
  tasks:
  - name: install jdk
    yum: name=java-1.8.0-openjdk state=installed
  - user:
      name: app
      comment: "The application admin."
      state: present
      password: "{{ app_user_password }}"
