- hosts: app
  become_user: app
  vars_files:
    - vars/common.yml
    - vars/app.yml
  vars_prompt:
    - name: "app_version"
      prompt: "Please enter the version of app to deploy"
      private: no
      confirm: no
  pre_tasks:
    - name: create common paths
      file:
        path: "{{item}}"
        state: directory
        mode: 0755
      with_items:
         - "{{app.installer_dir}}"
         - bin
         - logs
  roles:
    - stop_tomcat
    - deploy_app
    - start_tomcat
