- hosts: app
  become_user: root
  vars_files:
    - vars/common.yml
    - vars/app.yml
  vars_prompt:
  - name: "app_user_password"
    prompt: "Please enter the password of app user"
    private: yes
    confirm: yes
  tasks:
  - name: install jdk
    yum: name=java-1.8.0-openjdk state=installed
  - name: create app user
    user:
      name: app
      comment: "The application admin."
      state: present
      password: "{{ app_user_password }}"
  - name: create common paths
    file:
      path: "{{item}}"
      state: directory
      mode: 0755
    with_items:
       - "{{installer_dir}}"
       - bin
       - logs
