- hosts: app
  become_user: app
  vars_files:
    - vars/common.yml
    - vars/app.yml
  vars_prompt:
    - name: "app_version"
      prompt: "Please enter the version of app to deploy"
      private: no
      confirm: no
  roles:
    - stop_tomcat
    - deploy_app
    - start_tomcat
