- name: start tomcat
  shell: nohup ./startup.sh
  args:
    chdir: tomcat/bin/
  register: tomcat_startup
- debug:
    msg: "{{tomcat_startup.stdout}}"
- name: waiting for tomcat started
  wait_for:
    timeout: 120
    port: "{{app_server_port}}"
    state: started
- name: check app service is alived
  uri:
    url: "http://127.0.0.1:{{app_server_port}}/{{war.context}}"
    return_content: yes
    validate_certs: no
    status_code: 200,302
    timeout: 120
  register: app_status
- name: failed when server not running
  fail:
  when: "'CFETSIT' not in app_status.content"