tomcat:
  install_dir: .
  dir: ./tomcat
  version: 8.5.23
  java_opts: "-Dfile.encoding=UTF-8 -Djava.awt.headless=true -Xss256M -Xms512M "
  base_url: http://172.19.223.15:8081/artifactory/softwares/apache-tomcat

java_opts: " -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Xss256M -Xms512M "